version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www                # Código fonte + .env local disponível no container
      - ./storage/logs:/var/www/storage/logs  # logs persistidos fora do container
    ports:
      - "9000:9000"              # PHP-FPM escutando na porta 9000
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"                  # Porta 80 exposta para acessar Laravel via navegador
    volumes:
      - .:/var/www               # Código fonte para Nginx servir
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Config do Nginx personalizada
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"              # Porta 3306 para acesso externo (opcional)
    volumes:
      - dbdata:/var/lib/mysql    # Volume para persistir dados do MySQL
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
